# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

# stub: simple_delegate 0.0.2 ruby lib

Gem::Specification.new do |s|
  s.name = "simple_delegate"
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["kaspernj"]
  s.description = "A simple library to delegate methods to instance variables"
  s.email = "k@spernj.org"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = Dir["{app,config,db,lib}/**/*", "LICENSE.txt", "Rakefile", "README.md"]
  s.homepage = "http://github.com/kaspernj/simple_delegate"
  s.licenses = ["MIT"]
  s.metadata["rubygems_mfa_required"] = "true"
  s.required_ruby_version = ">= 2.7"
  s.summary = "A simple library to delegate methods to instance variables"

  s.add_development_dependency "best_practice_project"
  s.add_development_dependency "bundler"
  s.add_development_dependency "rake"
  s.add_development_dependency "rspec"
  s.add_development_dependency "rubocop"
  s.add_development_dependency "rubocop-performance"
  s.add_development_dependency "rubocop-rspec"
end
